### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by annymosse** [barrett-ruth/import-cost.nvim#14]
### Info

- Operating System:
- `nvim --version`: 0.9.5
- Node package manager:
- `node --version`: 20.12.2
- `npm --version`: 10.5.0
- `pnpm --version`: 9.0.6

### Configuration

```lua
require('import-cost').setup {
    -- as default config
}
```

### Description
the calculation always return 0.0b (gzipped: 0.0b) for all packages (ex: loadash, solid,...) even with huge packages or node std packages.

**Comment by barrett-ruth** [comment]
which package manager are you using?

**Comment by annymosse** [comment]
Hi @barrett-ruth thank you for this missing plugin in the `lazyVim` packages, and sorry for the delay.  
> which package manager are you using?

since `import-cost` depends on the flat structure & `pnpm` doesn't use `--shamefull-hoist` by default anymore, I had to go into the plugin directory and install the packages manually using `pnpm --shamefully-hoist` and tried it without success, thus I re-install the packages again using `npm` and I had same issue.

**Comment by barrett-ruth** [comment]
I just checked again. The plugin does work with `npm` but not with `pnpm` because workspaces aren't supported. Try deleting the plugin and reinstalling. I will denote this fact in the readme (I use pnpm myself after all).

**Comment by annymosse** [comment]
> I just checked again. The plugin does work with `npm` but not with `pnpm` because workspaces aren't supported. Try deleting the plugin and reinstalling. I will denote this fact in the readme (I use pnpm myself after all).

alright, after I used a docker container it works well (without using pnpm), it seems it's a problem in my npm global cache folder, since it worker after deleting it and tried again.
