### ISSUE TITLE
Nothing is appearing

### ISSUE THREAD

**Issue by lucax88x** [barrett-ruth/import-cost.nvim#5]
### Info

- Operating System: macos 12.6 
- NVIM v0.9.0-dev-1832+g08ebf8d3a-dirty
- Node package manager:
- v18.12.1

### Configuration

```lua
return {
  "barrett-ruth/import-cost.nvim",
  build = "sh install.sh npm",
  config = function()
    require("import-cost").setup({})
  end,
}
```

</details>

### Description
not appearing at all, do you need more info?
project is a pnpm one, but it still has a package.json

**Comment by barrett-ruth** [comment]
Replicate the issue with a single file in a new project please.

**Comment by barrett-ruth** [comment]
Sorry for the prod @lucax88x. Any updates on this?

**Comment by lucax88x** [comment]
Sorry bud, first day after vacations.

Looks like that using npm works fine, I was using pnpm before and didn't work, need to check it better.

Sorry to wasting your time.

**Comment by barrett-ruth** [comment]
The npm module has a lot of weird features and isn't very consistent. Glad you got it resolved, I'll add a note to the readme.

**Comment by ryoppippi** [comment]
@lucax88x 
Hi!
If you are interested, try to use bun to install dependencies!
It is really faster than pnpm

**Comment by ryoppippi** [comment]
Also, I think this problem comes from the lack of deps of import-cost.
You can contribute to import-cost itself

**Comment by barrett-ruth** [comment]
I recently switched to pnpm. And I don't think it's a good move to move to bun (yet). Tracking an upstream in pnpm.

**Comment by annymosse** [comment]
This maybe a helpful for someone, as a work around go to the neovim pluggins folder and reinstall the packages in a flat structure; in my case : 
```bash
cd ~/.local/share/nvim/lazy/import-cost/import-cost/
pnpm install --shamefully-hoist
```
to re-install the packages similarly to npm & yarn in a flat structure.

**Comment by netrolite** [comment]
> This maybe a helpful for someone, as a work around go to the neovim pluggins folder and reinstall the packages in a flat structure; in my case :
> 
> ```shell
> cd ~/.local/share/nvim/lazy/import-cost/import-cost/
> pnpm install --shamefully-hoist
> ```
> 
> to re-install the packages similarly to npm & yarn in a flat structure.

This didn't fix it for me unforutunately
